
services:

# MariaDB
  db_maria:
    image: mariadb:11
    container_name: "EDI_DB_MARIA"
    restart: unless-stopped
    env_file:
      - .env_w
    volumes:
      - db_maria_data:/var/lib/mysql
    networks:
      - wpsite

# PostgreSQL
  db_postgres:
    image: docker.io/postgres:10
    container_name: "EDI_DB_POSTGRES"
    restart: always
    env_file:
      - .env_l
    expose:
      - 5432
    volumes:
      - ./volumes/db_postgres_data:/var/lib/postgresql/data
    networks:
      - lsite

  # phpMyAdmin
  # phpMyAdmin for Wordpress and Moodle
  phpmyadmin:
    image: phpmyadmin
    container_name: "EDI_PHPMYADMIN"
    restart: always
    ports:
      - 8086:80
    environment:
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=100000000
    depends_on:
      - db_maria
    networks:
      - wpsite

  # pgAdmin for LimeSurvey
  pgadmin:
    image: dpage/pgadmin4
    container_name: "EDI_PGADMIN"
    restart: always
    ports:
      - 8004:80
    env_file:
      - .env_l
    volumes:
       - pgadmin_data:/var/lib/pgadmin
       - pgadmin_tmp:/tmp
    depends_on:
      - db_postgres
    links:
      - db_postgres
    networks:
      - lsite

  # --- FRONT-END ---
  # Wordpress
  # As the main platform
  wordpress:
    #image: wordpress:latest
    build:
      context: ./installation/wordpress
      dockerfile: Dockerfile-wordpress
    container_name: "EDI_WORDPRESS"
    hostname: platform.edideskproject.com
    volumes:
       - ./volume/wp_data/wp-content:/var/www/html/wp-content
    restart: always
    ports:
      - 8100:80
    environment:
      - .env_w
    depends_on:
      - db_maria
    networks:
      - wpsite

  # LimeSurvey
  # For user surveys
  limesurvey:
    image: docker.io/martialblog/limesurvey:latest
    container_name: "EDI_LIMESURVEY"
    restart: always
    env_file:
      - .env_l
    volumes:
      - ./volumes/limesurvey_data:/var/www/html/upload/surveys
    ports:
      - 8085:8080
    depends_on:
      - db_postgres
    links:
      - db_postgres
    networks:
      - lsite

  # --- MANAGEMENT ---

  # Portainer
  # For managing containers
  portainer:
    image: portainer/portainer-ce:latest
    container_name: "EDI_PORTAINER"
    hostname: platform.edideskproject.com
    restart: always
    ports:
      - 8000:8000
      - 9443:9443
      - 9000:9000
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./volumes/portainer_data:/data
    networks:
      - wpsite
      - lsite

  # Nginx Proxy Manager
  # For managing domains and certificates
  nginxproxymanager:
   image: 'jc21/nginx-proxy-manager:latest'
   container_name: "EDI_NGINXPROXYMANAGER"
   restart: always
   ports:
     - 80:80
     - 8083:81
     - 443:443
   volumes:
     - ./volumes/nginx_data:/data
     - ./volumes/letsencrypt_data:/etc/letsencrypt
   networks:
     - wpsite


volumes:
  db_maria_data:
  db_postgres_data:
  wp_data:
  limesurvey_data:
  nginx_data:
  letsencrypt_data:
  pgadmin_data:
  pgadmin_tmp:


networks:
  wpsite:
  lsite:
